services:
  - type: web
    name: fefusa-menores
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 5000
      - key: PROMOTION_SPOTS
        value: 2